### ISSUE TITLE
Show Error

### ISSUE THREAD

**Issue by MzkZeeshan** [mousedoc/nox-adb-connector#1]
unable to connect to 127.0.0.1:62001: cannot connect to 127.0.0.1:62001: No connection could be made because the target machine actively refused it. (10061)

**Comment by mousedoc** [comment]
Follow this [solution](https://www.bignox.com/blog/how-to-connect-android-studio-with-nox-app-player-for-android-development-and-debug/)

Thanx

**Comment by mousedoc** [comment]
> unable to connect to 127.0.0.1:62001: cannot connect to 127.0.0.1:62001: No connection could be made because the target machine actively refused it. (10061)

Try this [solution](https://www.bignox.com/blog/how-to-connect-android-studio-with-nox-app-player-for-android-development-and-debug/)
