### ISSUE TITLE
adb connect 127.0.0.1:62026

### ISSUE THREAD

**Issue by QGB** [mousedoc/nox-adb-connector#2]
``` 
Android版本7.1    adb connect 127.0.0.1:62026
Android版本5.1.1 adb connect 127.0.0.1:62001

```

**Comment by mousedoc** [comment]
Please add more information

**Comment by mousedoc** [comment]
> ```
> Android版本7.1    adb connect 127.0.0.1:62026
> Android版本5.1.1 adb connect 127.0.0.1:62001
> ```

Please add more information
